name: Scheduled Release

on:
  schedule:
    - cron: '0 10 * * 1'  # Every Monday at 10:00 UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes since last release
        id: changes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            echo "No previous tags found, marking as having changes"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Last tag: $LAST_TAG"
            CHANGES=$(git rev-list $LAST_TAG..HEAD --count)
            echo "Changes since last tag: $CHANGES"
            if [ $CHANGES -gt 0 ]; then
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Trigger Release Please workflow
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release-please.yml',
              ref: 'main'
            });
            console.log('✅ Triggered Release Please workflow');

      - name: No changes found
        if: steps.changes.outputs.has_changes == 'false'
        run: |
          echo "No changes found since last release. Skipping release creation."
